#!/usr/bin/env bash
# =============================================================================
# build.sh — bundle the whole app into ONE self-contained dist/index.html
# =============================================================================
# Why: some hosts (notably SharePoint document libraries) can't serve a folder
# of linked files — relative links to css/js/assets break and you get a blank
# page. This script inlines everything (CSS, JS, the data file, and every SVG)
# into a single HTML file with no external references, so it can be dropped
# anywhere as one file.
#
# Usage:   bash build.sh                 # bundles data/norcomm.js by default
#          bash build.sh data/other.js   # bundle a different center
#
# Output:  dist/index.html   (open it by double-click to verify)
#
# No Node/npm/Python needed — pure bash + base64 (both already on this machine).
# Re-run this whenever you change the app or the data and want a fresh bundle.
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"

DATA_FILE="${1:-data/norcomm.js}"
OUT_DIR="dist"
OUT="$OUT_DIR/index.html"

[ -f "$DATA_FILE" ] || { echo "ERROR: data file not found: $DATA_FILE" >&2; exit 1; }
mkdir -p "$OUT_DIR"

echo "Bundling '$DATA_FILE' -> $OUT"

# --- 1. Build window.ASSET_MAP from every .svg the data file references -------
# Each SVG becomes a base64 data: URI so it lives inside the HTML.
ASSET_JS="$(mktemp)"
trap 'rm -f "$ASSET_JS"' EXIT
echo "window.ASSET_MAP = {" > "$ASSET_JS"
count=0
# Pull the 40-char asset hashes out of the data file (connectors: asset: "...").
for hash in $(grep -oE 'asset: "[a-f0-9]{40}"' "$DATA_FILE" | grep -oE '[a-f0-9]{40}' | sort -u); do
  svg="assets/$hash.svg"
  if [ ! -f "$svg" ]; then
    echo "  WARNING: referenced asset missing, skipping: $svg" >&2
    continue
  fi
  b64=$(base64 -w0 "$svg" 2>/dev/null || base64 "$svg" | tr -d '\n')
  echo "  \"$hash\": \"data:image/svg+xml;base64,$b64\"," >> "$ASSET_JS"
  count=$((count + 1))
done
echo "};" >> "$ASSET_JS"
echo "  inlined $count SVG asset(s)"

# --- 2. Assemble the single HTML file ----------------------------------------
{
  echo '<!DOCTYPE html>'
  echo '<html lang="en">'
  echo '<head>'
  echo '  <meta charset="UTF-8" />'
  echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />'
  echo '  <title>Dispatch Workflow</title>'
  echo '  <!-- Bundled build: all CSS/JS/data/SVGs inlined. Generated by build.sh. -->'
  echo '  <style>'
  cat css/theme.css
  cat css/app.css
  echo '  </style>'
  echo '</head>'
  echo '<body>'
  # Body markup is extracted straight from index.html (the lines between <body>
  # and the first <script>), so the bundle NEVER drifts from the real page.
  # We drop index.html's <script src=...> tags because the bundle inlines all JS
  # right below instead.
  awk '
    /<body>/     { inbody=1; next }
    inbody && /<script/ { exit }   # stop at the external <script> tags
    inbody       { print }
  ' index.html
  echo '  <script>'
  cat "$ASSET_JS"        # window.ASSET_MAP (inlined SVGs) — must come first
  echo ''
  cat "$DATA_FILE"       # window.DISPATCH_CENTER
  echo ''
  cat js/diagram.js
  echo ''
  cat js/panels.js
  echo ''
  cat js/app.js
  echo '  </script>'
  echo '</body>'
  echo '</html>'
} > "$OUT"

bytes=$(wc -c < "$OUT")
echo "Done: $OUT ($bytes bytes). Double-click it to verify before uploading."
